### ISSUE TITLE
Boost::python: missing `init_module`

### ISSUE THREAD

**Issue by Axel-Naumann** [HDembinski/histogram#39] opened 2017-12-12 09:31 UTC
With
```
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   iostreams
--   serialization
--   python
--   numpy
-- Build type: RELEASE [optimizations on]
```
I get
```
Undefined symbols for architecture x86_64:
  "boost::python::detail::init_module(PyModuleDef&, void (*)())", referenced from:
      _PyInit_cpp_filler in guide_listing_16.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [cpp_filler.so] Error 1
```
That's on MacOS 10.13.1 with Xcode 9.2

**Comment by HDembinski** [comment] 2017-12-12 10:42
Hm, I am also developing on Mac, using the exact same setup. Do you have two installations of Python? It is important that both boost.python and this library are linked to the same version of the Python libraries.

**Comment by HDembinski** [comment] 2017-12-12 10:42
See https://github.com/davisking/dlib/issues/80 and solution

**Comment by HDembinski** [comment] 2017-12-12 10:44
If you have both Python 2 and 3 installed, cmake will probably detect Python 3. To force Python 2, you can pass the PYTHON_VERSION flag:
`cmake -DPYTHON_VERSION=2 [...]`
I am sorry for this inconvenience :(

**Comment by HDembinski** [comment] 2017-12-13 12:33
I further improved the build script to support python3 on Mac. It seems that Boost.Python uses the name python3 for the python component if it was compiled against Python3. So I can detect that. I cannot detect whether Boost.Numpy is also compiled to the correct Python libraries.

**Comment by HDembinski** [comment] 2017-12-14 12:34
Which cmake version are you using? In my case it is 3.9.6. In this version, find_package(PythonInterp) looks for the version string found by find_package(PythonLibs) automatically. I just committed a change to the CMakeLists.txt, to make sure this is done. I hope this helps.
Could you please try to update your working copy to current master, wipe the build directory completely, then do `cmake -DBOOST_ROOT=/Users/axel/build/boost/inst/ ../src/build/ -DPYTHON_VERSION=2` and let me know whether that works?

**Comment by HDembinski** [comment] 2018-03-06 21:47
@Axel-Naumann could you try again with the latest master and the new instructions in the README?

**Comment by HDembinski** [comment] 2018-03-10 19:26
I assume the issue is fixed, please re-open if not :)

**Closed by HDembinski** 2018-03-10 19:26 UTC
